# Generated by Django 3.1 on 2020-08-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20200815_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='amount',
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floor',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='rate',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='room',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='square_metre',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
