# Generated by Django 3.1 on 2020-08-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20200817_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.FloatField(blank=True),
        ),
    ]
